projectId: xlr8s-demo
envId: dev

K8sAllowedRepos:
  - name: allow-repos
    severity: high
    params:
      repos:
        - gcr.io/xebia
    enforcementAction: dryrun
    filters:
      labels: 
        app : nginx
      namespaces: ["default"]
      excludedNamespaces: ["kube-system", "kube-public", "kube-node-lease", "gatekeeper-system"]

K8sBlockNpLb:
  - name: block-node-port
    severity: high
    enforcementAction: dryrun
    params: {}
    filters:
      labels: 
        app : nginx
      namespaces: ["default"]
      excludedNamespaces: ["kube-system", "kube-public", "kube-node-lease", "gatekeeper-system"]


K8sCapsOnDeployment:
  - name: deployment-must-have-caps
    severity: high
    enforcementAction: dryrun
    params: 
      minReplicas: 3
    filters:
      labels: 
        app : nginx
      namespaces: ["default"]
      excludedNamespaces: ["kube-system", "kube-public", "kube-node-lease", "gatekeeper-system"]

K8sCapsOnHPA:
  - name: hpa-must-have-caps
    severity: high
    enforcementAction: dryrun
    params: 
      minReplicas: 3
      maxReplicas: 10
    filters:
      labels: 
        app : nginx
      namespaces: ["default"]
      excludedNamespaces: ["kube-system", "kube-public", "kube-node-lease", "gatekeeper-system"]


K8sContainerResourceLimits:
  - name: deployment-must-have-resource-limits
    severity: high
    enforcementAction: dryrun
    params: 
      requiredResourceTypes: ["limits", "requests"]
      requiredResources: ["cpu", "memory"]
      resourceLimits: 
        limits:
          cpu: "100m"
          memory: "1Gi"
        requests:
          cpu: "100m"
          memory: "1Gi"
    filters:
      labels: 
        app : nginx
      namespaces: ["default"]
      excludedNamespaces: ["kube-system", "kube-public", "kube-node-lease", "gatekeeper-system"]

K8sDisableHostNetworking:
  - name: pods-should-not-have-host-network
    severity: high
    enforcementAction: dryrun
    params: {}
    filters:
      labels: 
        app : nginx
      namespaces: ["default"]
      excludedNamespaces: ["kube-system", "kube-public", "kube-node-lease", "gatekeeper-system"]

K8sDisallowedTags:
  - name: container-image-must-not-have-following-tags
    severity: high
    enforcementAction: dryrun
    params: 
      tags: ["latest"]
    filters:
      labels: 
        app : nginx
      namespaces: []
      excludedNamespaces: ["kube-system", "kube-public", "kube-node-lease", "gatekeeper-system"]

K8sDisallowHostPath:
  - name: hostpath-volumns-not-allowed
    severity: high
    enforcementAction: dryrun
    params: {}
    filters:
      labels: 
        app: nginx
      namespaces: []
      excludedNamespaces: ["kube-system", "kube-public", "kube-node-lease", "gatekeeper-system"]

K8sDisallowedCapabilities:
  - name: disallow-capabilities
    severity: high
    enforcementAction: deny
    params: 
      disAllowedAddCapabilies: ["NET_ADMIN"]
      disAllowedDropCapabilies: []
      skipContainers: ["istio-init"]
    filters:
      labels: {}
      namespaces: []
      excludedNamespaces: ["kube-system", "kube-public", "kube-node-lease", "istio-system"]

K8sDisallowPrivilegedPods:
  - name: container-must-not-run-as-privileged
    severity: high
    enforcementAction: dryrun
    params: {}
    filters:
      labels: 
        app : nginx
      namespaces: []
      excludedNamespaces: ["kube-system", "kube-public", "kube-node-lease", "gatekeeper-system"]

K8sEnableAutoscaling:
  - name: deployment-must-have-autoscaling
    severity: high
    enforcementAction: dryrun
    params: {}
    filters:
      labels: 
        app : nginx
      namespaces: []
      excludedNamespaces: ["kube-system", "kube-public", "kube-node-lease", "gatekeeper-system"]

K8sPodPriority:
  - name: pod-must-have-priority
    severity: high
    enforcementAction: dryrun
    params: {}
    filters:
      labels: 
        app : nginx
      namespaces: ["default"]
      excludedNamespaces: ["kube-system", "kube-public", "kube-node-lease", "gatekeeper-system"]

K8sRequiredNamespace:
  - name: resources-must-have-namespace
    severity: high
    enforcementAction: dryrun
    params: {}
    filters:
      labels: 
        app: nginx
      namespaces: []
      excludedNamespaces: ["kube-system", "kube-public", "kube-node-lease", "gatekeeper-system"]

K8sRequiredProbes:
  - name: must-have-probes
    severity: high
    enforcementAction: dryrun
    params: 
      probes: ["readinessProbe", "livenessProbe", "startupProbe"]
      probeTypes: ["tcpSocket", "httpGet", "exec"]
    filters:
      labels: 
        app : nginx
      namespaces: ["default"]
      excludedNamespaces: ["kube-system", "kube-public", "kube-node-lease", "gatekeeper-system"]

K8sRunAsNonRoot:
  - name: container-must-run-as-non-root
    severity: high
    enforcementAction: dryrun
    params: 
      skipContainers: ["istio-init"]
    filters:
      labels: 
        app : nginx
      namespaces: ["default"]
      excludedNamespaces: ["kube-system", "kube-public", "kube-node-lease", "gatekeeper-system"]

