apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-pvc
  namespace: {{ .Values.namespace }}
spec:
  {{ if .Values.volume.storageClassName}}
  storageClassName: {{ .Values.volume.storageClassName }}
  {{ end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.storage }}
